### ISSUE TITLE
empty <span></span> at the begining of the highlight since 2.1.1

### ISSUE THREAD

**Issue by Anteru** [pygments/pygments-migration-test#961]
(Original issue 1254 created by andre_felipe_dias on 2016-07-09T15:45:07.328838+00:00)

Since v.2.1.1, the hightlight output starts with an empty span tag.

Steps to reproduce:

```python
#!/usr/bin/python3

from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters import HtmlFormatter

def pygmentize(code, language, **kwargs):
    lexer = get_lexer_by_name(language)
    formatter = HtmlFormatter(**kwargs)
    return highlight(code, lexer, formatter)

code = 'print("hello world")'
print(pygmentize(code, 'python'))

code = '# comment'
print(pygmentize(code, 'bash'))
```
at Pygments 2.1 and before, the output is:

```html
<div class="highlight"><pre><span class="k">print</span><span class="p">(</span><span class="s2">&quot;hello world&quot;</span><span class="p">)</span>
</pre></div>

<div class="highlight"><pre><span class="c1"># comment</span>
</pre></div>
```
Since Pygments 2.1.1, the output is:

```html
<div class="highlight"><pre><span></span><span class="k">print</span><span class="p">(</span><span class="s2">&quot;hello world&quot;</span><span class="p">)</span>
</pre></div>

<div class="highlight"><pre><span></span><span class="c1"># comment</span>
</pre></div>
```

Note the empty span tag just after `<pre>`. It doesn't look right.

**Comment by Anteru** [comment]
(Original issue 1254 last updated on 2016-08-26T00:26:47.985372+00:00)

(Issue automaticaly closed due to status in Bitbucket: wontfix)

**Comment by Anteru** [comment]
(Original comment by brondsem on 2016-08-25T22:50:51.022989+00:00)

Looks like it was changed in 164574c intentionally to fix #1111.  Would be nice if there was a cleaner way though, maybe only add the span tags when necessary?

**Comment by Anteru** [comment]
(Original comment by andre_felipe_dias on 2016-08-26T00:13:49.339909+00:00)

It is a good reason indeed. Probably, changing the current implementation is not worth the trouble.

**Comment by verhovsky** [comment]
Would be nice if this was fixed.

**Comment by ericpruitt** [comment]
> Would be nice if this was fixed.

Not a proper fix, but it's straightforward to filter them out with a regex:

```
EMPTY_SPAN_REGEX = re.compile("<span( [^>]*)?></span>", re.IGNORECASE)
...
result = EMPTY_SPAN_REGEX.sub("", html)
```
